routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CategorySectionController;
use App\Http\Controllers\Admin\ClientsController;
use App\Http\Controllers\Admin\GuestOrderController as GuestOrderControllerForAdmin;
use App\Http\Controllers\Admin\InvoiceController;
use App\Http\Controllers\Admin\PackagesController;
use App\Http\Controllers\Admin\PageGalleryController;
use App\Http\Controllers\Admin\PagesController as AdminPagesController;
use App\Http\Controllers\Admin\PageTabsController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\PortfoliosController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\ServicesController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\SubcategoryController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Buyer\ChatController;
use App\Http\Controllers\Buyer\OrderController;
use App\Http\Controllers\Website\OrderController as GuestOrderController;
use App\Http\Controllers\PayPalController;
use App\Http\Controllers\Website\PagesController;
use Illuminate\Support\Facades\Route;
use Spatie\MediaLibrary\MediaCollections\Models\Media as MediaAlias;

// cache clear
Route::get('reboot', function () {
  Artisan::call('cache:clear');
  Artisan::call('view:clear');
  Artisan::call('route:clear');
  Artisan::call('config:clear');
  Artisan::call('config:cache');
  Artisan::call('view:cache');
  dd('Done');
});

Route::get('storageLink', function () {
  Artisan::call('storage:link');
  dd('Done');
});

Route::get('migrate', function () {
  Artisan::call('migrate');
  dd('Done');
});

Route::get('cancel', [PayPalController::class, 'cancel'])->name('payment.cancel');
Route::get('payment/success', [PayPalController::class, 'success'])->name('payment.success');

Route::get('pay_invoice/{invoice}/{token}', [InvoiceController::class, 'invoicePayView'])->name('invoice.pay.view');

Route::prefix('dashboard')->middleware(['auth', 'verified'])->group(function () {
  Route::view('/', 'dashboard.dashboard')->name('dashboard');
  Route::resource('tag', TagController::class);
  Route::resource('category', CategoryController::class);
  Route::resource('subcategory', SubcategoryController::class);
  Route::resource('post', PostController::class);
  Route::resource('order', OrderController::class);
  Route::get('guest-order', [GuestOrderControllerForAdmin::class, 'showGuestOrders'])->name('guest.orders');
  Route::get('guest-order/{guestOrder}', [GuestOrderControllerForAdmin::class, 'showGuestOrderDetails'])->name('guest.orders.details');
  Route::post('guest-order/{guestOrder}/update-status', [GuestOrderControllerForAdmin::class, 'changeOrderStatus'])->name('guest.orders.update-status');
  Route::delete('guest-order/{guestOrder}/delete', [GuestOrderControllerForAdmin::class, 'deleteGuestOrder'])->name('guest.orders.delete');
  Route::resource('user', UserController::class);
  Route::resource('chat', ChatController::class);
  Route::resource('clients', ClientsController::class);
  Route::resource('portfolios', PortfoliosController::class);
  Route::resource('slider', SliderController::class);
  Route::resource('services', ServicesController::class);
  Route::get('invoice/pay/{invoice}', [InvoiceController::class, 'pay'])->name('invoice.pay');
  Route::resource('invoice', InvoiceController::class);
  Route::post('admin_chat', [ChatController::class, 'adminChat'])->name('admin.chat');
  Route::resource('settings/categorysection', CategorySectionController::class);
  Route::get('change_password', [UserController::class, 'change_password'])->name('change_password');
  Route::get('settings/company_settings', [SettingController::class, 'editCompanySetting'])->name('company.edit');
  Route::post('settings/company_setting', [SettingController::class, 'updateCompanySetting'])->name('company.update');
  Route::get('payLater/{order}', [OrderController::class, 'payLater'])->name('payLater.update');
  Route::post('changeOrderStatus/{order}', [OrderController::class, 'changeOrderStatus'])->name('changeOrderStatus');

  Route::prefix('website-settings')->group(function () {
    Route::resource('pages', AdminPagesController::class)->except(['show']);
    Route::prefix('pages/{page}')->group(function () {
      Route::put('packages/update-info', [PackagesController::class, 'updatePackageInfo'])->name('packages.update-info');
      Route::get('packages/get-package-info/{package}', [PackagesController::class, 'getPackageInfo']);
      Route::resource('packages', PackagesController::class)->except(['show', 'create', 'edit']);

      Route::get('gallery', [PageGalleryController::class, 'getPageGallery'])->name('pages.gallery');
      Route::put('gallery', [PageGalleryController::class, 'updatePageGallery']);

      Route::get('tabs', [PageTabsController::class, 'getPageTabs'])->name('pages.tabs');
      Route::put('tabs', [PageTabsController::class, 'updatePageTabs']);
    });
  });

  Route::delete('remove-media/{media}', function (MediaAlias $media) {
    $media->delete();
    return back()->with('success', 'Media successfully deleted.');
  })->name('remove-media');

  //Buyer & Reseller
  Route::get('guest_post', [\App\Http\Controllers\Buyer\PostController::class, 'allPost'])->name('guest_post.index');
  Route::get('guest_post/{post}', [\App\Http\Controllers\Buyer\PostController::class, 'viewPost'])->name('guest_post.view');
  Route::get('reseller_order', [\App\Http\Controllers\Buyer\PostController::class, 'resellerOrder'])->name('reseller_order.create');

  // Role Permission
  Route::resource('developer/permission', PermissionController::class);
  Route::get('role/assign', [RoleController::class, 'roleAssign'])->name('role.assign');
  Route::post('role/assign', [RoleController::class, 'storeAssign'])->name('store.assign');
  Route::resource('role', RoleController::class);

  //ajax
  Route::post('getSubcategory', [CategoryController::class, 'categorySubcategory'])->name('load.subcategory');
  Route::post('editSubcategory', [CategoryController::class, 'categoryEditSubcategory'])->name('edit.subcategory');
});

// Website routes
Route::get('purchase/{package}', [GuestOrderController::class, 'showAmountSelectionPage'])->name('package.purchase');
Route::post('purchase/{package}', [GuestOrderController::class, 'submitAmount']);
Route::get('purchase/{package}/{amount}/confirm-and-payment', [GuestOrderController::class, 'showConfirmAndPaymentPage'])->name('package.purchase.place-order');
Route::post('purchase/{package}/{amount}/confirm-and-payment', [GuestOrderController::class, 'placeOrder']);
Route::any('/{page:slug?}', [PagesController::class, 'showPages'])->name('page')->where('slug', '.*');

app/Http/Livewire/Dashboard/CartCount.php
<?php

namespace App\Http\Livewire\Dashboard;

use Gloudemans\Shoppingcart\Facades\Cart;
use Livewire\Component;

class CartCount extends Component
{
  public $show = false;
  public $cart_count = 0;

  protected $listeners = ['notify' => 'updateCount'];

  public function mount()
  {
    $this->updateCount();
  }

  public function updateCount()
  {
    $this->cart_count = Cart::count();

    if ($this->cart_count > 0) {
      $this->show = true;
    } else {
      $this->show = false;
    }
  }

  public function render()
  {
    return view('livewire.dashboard.cart-count');
  }
}

app/Http/Livewire/Dashboard/ShoppingCart.php
<?php

namespace App\Http\Livewire\Dashboard;

use App\Models\Post;
use Gloudemans\Shoppingcart\Facades\Cart;
use Livewire\Component;

class ShoppingCart extends Component
{
  protected $listeners = ['add-to-cart' => 'addToCart'];

  public function render()
  {
    return view('livewire.dashboard.shopping-cart');
  }

  public function addToCart(Post $post)
  {
    if (Cart::content()->where('id', $post->id)->first()) {
      $this->emit('notify', 'Item already in cart.');
      return;
    }
    Cart::add($post->id, $post->url, 1, $post->reseller_price);
    $this->emit('notify', 'Item added to your cart.');
  }

  public function remove($rowId)
  {
    Cart::remove($rowId);
    $this->emit('notify', 'Item removed from your cart.');
  }
}

resources/views/layouts/includes/dashboard/menu/buyer.blade.php
<ul class="menu-nav">
  <li class="menu-item {{ request()->is('dashboard') ? 'menu-item-active' : null }}" aria-haspopup="true">
    <a href="{{ route('dashboard') }}" class="menu-link">
      <span class="svg-icon menu-icon">
        <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <polygon points="0 0 24 0 24 24 0 24"/>
            <path d="M12.9336061,16.072447 L19.36,10.9564761 L19.5181585,10.8312381 C20.1676248,10.3169571 20.2772143,9.3735535 19.7629333,8.72408713 C19.6917232,8.63415859 19.6104327,8.55269514 19.5206557,8.48129411 L12.9336854,3.24257445 C12.3871201,2.80788259 11.6128799,2.80788259 11.0663146,3.24257445 L4.47482784,8.48488609 C3.82645598,9.00054628 3.71887192,9.94418071 4.23453211,10.5925526 C4.30500305,10.6811601 4.38527899,10.7615046 4.47382636,10.8320511 L4.63,10.9564761 L11.0659024,16.0730648 C11.6126744,16.5077525 12.3871218,16.5074963 12.9336061,16.072447 Z"
              fill="#000000" fill-rule="nonzero"/>
            <path d="M11.0563554,18.6706981 L5.33593024,14.122919 C4.94553994,13.8125559 4.37746707,13.8774308 4.06710397,14.2678211 C4.06471678,14.2708238 4.06234874,14.2738418 4.06,14.2768747 L4.06,14.2768747 C3.75257288,14.6738539 3.82516916,15.244888 4.22214834,15.5523151 C4.22358765,15.5534297 4.2250303,15.55454 4.22647627,15.555646 L11.0872776,20.8031356 C11.6250734,21.2144692 12.371757,21.2145375 12.909628,20.8033023 L19.7677785,15.559828 C20.1693192,15.2528257 20.2459576,14.6784381 19.9389553,14.2768974 C19.9376429,14.2751809 19.9363245,14.2734691 19.935,14.2717619 L19.935,14.2717619 C19.6266937,13.8743807 19.0546209,13.8021712 18.6572397,14.1104775 C18.654352,14.112718 18.6514778,14.1149757 18.6486172,14.1172508 L12.9235044,18.6705218 C12.377022,19.1051477 11.6029199,19.1052208 11.0563554,18.6706981 Z"
              fill="#000000" opacity="0.3"/>
          </g>
        </svg>
      </span>
      <span class="menu-text">Dashboard</span>
    </a>
  </li>

  <li class="menu-section">
    <h4 class="menu-text">Website</h4>
    <i class="menu-icon ki ki-bold-more-hor icon-md"></i>
  </li>

  <li class="menu-item {{ request()->is('dashboard/guest_post*') ? 'menu-item-active' : null }}" aria-haspopup="true">
    <a href="{{ route('guest_post.index') }}" class="menu-link">
      <span class="svg-icon menu-icon">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <rect x="0" y="0" width="24" height="24"/>
            <path d="M6,9 L6,15 C6,16.6568542 7.34314575,18 9,18 L15,18 L15,18.8181818 C15,20.2324881 14.2324881,21 12.8181818,21 L5.18181818,21 C3.76751186,21 3,20.2324881 3,18.8181818 L3,11.1818182 C3,9.76751186 3.76751186,9 5.18181818,9 L6,9 Z" fill="#000000" fill-rule="nonzero"/>
            <path d="M10.1818182,4 L17.8181818,4 C19.2324881,4 20,4.76751186 20,6.18181818 L20,13.8181818 C20,15.2324881 19.2324881,16 17.8181818,16 L10.1818182,16 C8.76751186,16 8,15.2324881 8,13.8181818 L8,6.18181818 C8,4.76751186 8.76751186,4 10.1818182,4 Z" fill="#000000" opacity="0.3"/>
          </g>
        </svg>
      </span>
      <span class="menu-text">Guest Post</span>
    </a>
  </li>
  <li class="menu-item {{ request()->is('dashboard/order*') ? 'menu-item-active' : null }}" aria-haspopup="true">
    <a href="{{ route('order.index') }}" class="menu-link">
      <span class="svg-icon menu-icon">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <rect x="0" y="0" width="24" height="24"/>
            <path d="M5.5,4 L9.5,4 C10.3284271,4 11,4.67157288 11,5.5 L11,6.5 C11,7.32842712 10.3284271,8 9.5,8 L5.5,8 C4.67157288,8 4,7.32842712 4,6.5 L4,5.5 C4,4.67157288 4.67157288,4 5.5,4 Z M14.5,16 L18.5,16 C19.3284271,16 20,16.6715729 20,17.5 L20,18.5 C20,19.3284271 19.3284271,20 18.5,20 L14.5,20 C13.6715729,20 13,19.3284271 13,18.5 L13,17.5 C13,16.6715729 13.6715729,16 14.5,16 Z" fill="#000000"/>
            <path d="M5.5,10 L9.5,10 C10.3284271,10 11,10.6715729 11,11.5 L11,18.5 C11,19.3284271 10.3284271,20 9.5,20 L5.5,20 C4.67157288,20 4,19.3284271 4,18.5 L4,11.5 C4,10.6715729 4.67157288,10 5.5,10 Z M14.5,4 L18.5,4 C19.3284271,4 20,4.67157288 20,5.5 L20,12.5 C20,13.3284271 19.3284271,14 18.5,14 L14.5,14 C13.6715729,14 13,13.3284271 13,12.5 L13,5.5 C13,4.67157288 13.6715729,4 14.5,4 Z" fill="#000000" opacity="0.3"/>
          </g>
        </svg>
      </span>
      <span class="menu-text">Orders</span>
    </a>
  </li>
  <li class="menu-item {{ request()->is('dashboard/chat*') ? 'menu-item-active' : null }}" aria-haspopup="true">
    <a href="{{ route('chat.create') }}" class="menu-link">
      <span class="svg-icon menu-icon">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <rect x="0" y="0" width="24" height="24"/>
            <path d="M16,15.6315789 L16,12 C16,10.3431458 14.6568542,9 13,9 L6.16183229,9 L6.16183229,5.52631579 C6.16183229,4.13107011 7.29290239,3 8.68814808,3 L20.4776218,3 C21.8728674,3 23.0039375,4.13107011 23.0039375,5.52631579 L23.0039375,13.1052632 L23.0206157,17.786793 C23.0215995,18.0629336 22.7985408,18.2875874 22.5224001,18.2885711 C22.3891754,18.2890457 22.2612702,18.2363324 22.1670655,18.1421277 L19.6565168,15.6315789 L16,15.6315789 Z" fill="#000000"/>
            <path d="M1.98505595,18 L1.98505595,13 C1.98505595,11.8954305 2.88048645,11 3.98505595,11 L11.9850559,11 C13.0896254,11 13.9850559,11.8954305 13.9850559,13 L13.9850559,18 C13.9850559,19.1045695 13.0896254,20 11.9850559,20 L4.10078614,20 L2.85693427,21.1905292 C2.65744295,21.3814685 2.34093638,21.3745358 2.14999706,21.1750444 C2.06092565,21.0819836 2.01120804,20.958136 2.01120804,20.8293182 L2.01120804,18.32426 C1.99400175,18.2187196 1.98505595,18.1104045 1.98505595,18 Z M6.5,14 C6.22385763,14 6,14.2238576 6,14.5 C6,14.7761424 6.22385763,15 6.5,15 L11.5,15 C11.7761424,15 12,14.7761424 12,14.5 C12,14.2238576 11.7761424,14 11.5,14 L6.5,14 Z M9.5,16 C9.22385763,16 9,16.2238576 9,16.5 C9,16.7761424 9.22385763,17 9.5,17 L11.5,17 C11.7761424,17 12,16.7761424 12,16.5 C12,16.2238576 11.7761424,16 11.5,16 L9.5,16 Z" fill="#000000" opacity="0.3"/>
          </g>
        </svg>
      </span>
      <span class="menu-text">Chat With Admin</span>
      @php($count_message = \App\Models\Chat::where(['receiver_id' => auth()->id(), 'status' => 0])->count())
      @if($count_message)
      <span class="menu-label">
        <span class="label label-primary label-inline">{{ $count_message }}</span>
      </span>
      @endif
    </a>
  </li>
  <li class="menu-item {{ request()->is(['dashboard/user*', 'dashboard/change_password']) ? 'menu-item-active' : null }}" aria-haspopup="true">
    <a href="{{ route('user.edit', auth()->id()) }}" class="menu-link">
      <span class="svg-icon menu-iconx">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <polygon points="0 0 24 0 24 24 0 24"/>
            <path d="M12,11 C9.790861,11 8,9.209139 8,7 C8,4.790861 9.790861,3 12,3 C14.209139,3 16,4.790861 16,7 C16,9.209139 14.209139,11 12,11 Z" fill="#000000" fill-rule="nonzero" opacity="0.3"/>
            <path d="M3.00065168,20.1992055 C3.38825852,15.4265159 7.26191235,13 11.9833413,13 C16.7712164,13 20.7048837,15.2931929 20.9979143,20.2 C21.0095879,20.3954741 20.9979143,21 20.2466999,21 C16.541124,21 11.0347247,21 3.72750223,21 C3.47671215,21 2.97953825,20.45918 3.00065168,20.1992055 Z" fill="#000000" fill-rule="nonzero"/>
          </g>
        </svg>
      </span>
      <span class="menu-text">Profile</span>
    </a>
  </li>
</ul>